name: Test pull request
on: pull_request
jobs:
  setup-validation:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: sudo apt-get install graphviz graphviz-dev
      - name: Run make setup
        run: make setup
      - name: Verify no pip dependency conflicts
        run: |
          . .venv/bin/activate
          pip check
  tox:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        python: ['3.9', '3.10', '3.11', '3.12', '3.13']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: pip install --upgrade pip
      - run: sudo apt-get install graphviz graphviz-dev
      - run: pip install tox
      - run: tox -e py
  test-postgres:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: sudo apt-get install graphviz graphviz-dev
      - run: make test-postgres
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: sudo apt-get install graphviz graphviz-dev
      - run: make lint
