name: Test pull request
on: pull_request
jobs:
  tox:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        # Pinned to ubuntu-20.04 as that is the last version to include Python 3.6 support.
        os: [ubuntu-20.04]
        python: ['3.7', '3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install --upgrade pip
      - run: sudo apt-get install graphviz graphviz-dev
      - run: pip install tox
      - run: tox -e py
  test-postgres:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./pytest.sh
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./lint.sh
