name: Test pull request
on: pull_request
jobs:
  tox:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # Pinned to ubuntu-22.04 as that is the last version to include Python 3.8 support.
        # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#python
        os: [ubuntu-22.04]
        python: ['3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: pip install --upgrade pip
      - run: sudo apt-get install graphviz graphviz-dev
      - run: pip install tox
      - run: tox -e py
  test-postgres:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: sudo apt-get install graphviz graphviz-dev
      - run: make test-postgres
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: sudo apt-get install graphviz graphviz-dev
      - run: make lint
